version: '3.6'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    volumes:
      - ./docker/:/data/postgres
    ports:
      - ${DATABASE_PORT}:5432